module.exports = {
    "New England Patriots": "17",
    "Buffalo Bills": "2",
    "Chicago Bears": "3",
    "Washington Football Team": "28",
    "Houston Texans": "34",
    "Miami Dolphins": "15",
    "New York Jets": "20",
    "Green Bay Packers": "9",
    "Minnesota Vikings": "16",
    "Detroit Lions": "8",
    "Arizona Cardinals": "22",
    "Los Angeles Rams": "14",
    "Los Anglees Chargers": "24",
    "Las Vegas Raiders": "13",
    "Denver Broncos": "7",
    "Dallas Cowboys": "6",
    "Seattle Seahawks": "26",
    "Kansas City Chiefs": "12",
    "Pittsburgh Steelers": "23",
    "Philadelphia Eagles": "21",
    "New York Giants": "19",
    "Atlanta Falcons": "1",
    "Carolina Panthers": "29",
    "New Orleans Saints": "18",
    "Jacksonville Jaguars": "30",
    "Tampa Bay Buccaneers": "27",
    "Tennessee Titans": "10",
    "Cincinatti Bengals": "4",
    "Cleveland Browns": "5",
    "Indianapolis Colts": "11",
    "San Francisco 49ers": "25",
    "Baltimore Ravens": "33"
}